title: Safer Internet Pledge
description: This is a voluntary pledge on Abuse Management, focused on enterprise software products and services, including on-premises software, cloud services, and software as a service (SaaS).
show_downloads: false
# google_analytics:
theme: jekyll-theme-cayman